version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: VuejsTodo
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always